<template>
  <div class="loadingio-spinner-ellipsis-lfrw2kbohkd">
    <div class="ldio-p9xpi3qu7v">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-p9xpi3qu7v {
  0% {
    transform: translate(3.42px, 42.18px) scale(0);
  }
  25% {
    transform: translate(3.42px, 42.18px) scale(0);
  }
  50% {
    transform: translate(3.42px, 42.18px) scale(1);
  }
  75% {
    transform: translate(42.18px, 42.18px) scale(1);
  }
  100% {
    transform: translate(80.94px, 42.18px) scale(1);
  }
}

@keyframes ldio-p9xpi3qu7v-r {
  0% {
    transform: translate(80.94px, 42.18px); scale(1):
  }
  100% {
    transform: translate(80.94px, 42.18px) scale(0);
  }
}

@keyframes ldio-p9xpi3qu7v-c {
  0% {
    background: #d84b55
  }
  25% {
    background: #648123
  }
  50% {
    background: #bf6504
  }
  75% {
    background: #fc572c
  }
  100% {
    background: #d84b55
  }
}

.ldio-p9xpi3qu7v div {
  position: absolute;
  width: 29.639999999999997px;
  height: 29.639999999999997px;
  border-radius: 50%;
  transform: translate(42.18px, 42.18px) scale(1);
  background: #d84b55;
  animation: ldio-p9xpi3qu7v 1.5873015873015872s infinite cubic-bezier(0, 0.5, 0.5, 1);
}

.ldio-p9xpi3qu7v div:nth-child(1) {
  background: #f8714f;
  transform: translate(80.94px, 42.18px) scale(1);
  animation: ldio-p9xpi3qu7v-r 0.3968253968253968s infinite cubic-bezier(0, 0.5, 0.5, 1), ldio-p9xpi3qu7v-c 1.5873015873015872s infinite step-start;
}

.ldio-p9xpi3qu7v div:nth-child(2) {
  animation-delay: -0.3968253968253968s;
  background: #d84b55;
}

.ldio-p9xpi3qu7v div:nth-child(3) {
  animation-delay: -0.7936507936507936s;
  background: #f8714f;
}

.ldio-p9xpi3qu7v div:nth-child(4) {
  animation-delay: -1.1904761904761905s;
  background: #f2a24f;
}

.ldio-p9xpi3qu7v div:nth-child(5) {
  animation-delay: -1.5873015873015872s;
  background: #648123;
}

.loadingio-spinner-ellipsis-lfrw2kbohkd {
  width: 114px;
  height: 114px;
  display: inline-block;
  overflow: hidden;
  background: none;
}

.ldio-p9xpi3qu7v {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}

.ldio-p9xpi3qu7v div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>
